project:
  output-dir: _output
format:
  html:
    toc: true              # md to exclude: {.unnumbered .unlisted}
    toc-depth: 3
    toc-expand: 2
    number-sections: true  # md to exclude: {.unnumbered}
    number-depth: 3
    code-fold: true
    code-tools: true
    embed-resources: false # true for standalone
date: now
date-format: "YYYY-MM-DD HH:mm:ss"
editor: source
editor_options:
  chunk_output_type: console
bibliography: msens.bib
bibliographystyle: apa
