---
title: "ingest_fisheries.noaa.gov_critical-habitat"
editor_options: 
  chunk_output_type: console
---

- [National ESA Critical Habitat Mapper | NOAA Fisheries](https://www.fisheries.noaa.gov/resource/map/national-esa-critical-habitat-mapper)
  - Downloaded Geodatabase
  - [Threatened and Endangered Species List—Gulf of America | NOAA Fisheries](https://www.fisheries.noaa.gov/southeast/consultations/threatened-and-endangered-species-list-gulf-america)

```{r}
#| label: setup

librarian::shelf(
  dplyr, DT, glue, here, mapview, purrr, sf,
  quiet = T)

mapviewOptions(
  basemaps       = "Esri.OceanBasemap",
  vector.palette = \(n) grDevices::hcl.colors(n, palette = "Spectral") )

gdb <- "~/My Drive/projects/msens/data/raw/fisheries.noaa.gov/NMFS_ESA_Critical_Habitat_20230505.gdb"
```

```{r}
#| label: layers

d_lyrs <- st_layers(gdb) |> 
  tibble() |> 
  mutate(
    crs      = map_chr(crs, ~ st_crs(.x)$input),
    geomtype = unlist(geomtype)) |> 
  select(-driver) |> 
  arrange(name)

table(d_lyrs$geomtype)

d_lyrs |> 
  datatable()
```

```{r}
#| label: lines

lns <- st_read(gdb, layer = "All_critical_habitat_line_20220404", quiet = T) #|> 
  # tibble() |> 
  # st_as_sf()
table(lns$COMNAME)

"Seal, Hawaiian monk"

"Sturgeon, Gulf"
"Sturgeon, Atlantic"

lns_hi <- lns |> 
  filter(COMNAME == "Seal, Hawaiian monk")
mapView(lns)
plot(lns_hi["COMNAME"])

```

```{r}
#| label: polygons

ply <- st_read(gdb, layer = "All_critical_habitat_poly_20230724", quiet = T) |> 
  tibble() |> 
  st_as_sf()


mapView(ply, alpha.regions = 0.6, zcol = "COMNAME")

ply |> 
  tibble() |> 
  select(-Shape) |> 
  datatable()
```

