---
title: "view_maps"
editor_options: 
  chunk_output_type: console
format: 
  html:
    code-fold: show
---

* [addProviderTiles work but Esri.OceanBasemap option suddenly does not work · Issue #841 · rstudio/leaflet](https://github.com/rstudio/leaflet/issues/841#issuecomment-1442032371)

```{r}
library(leaflet)

m <- leaflet() |>
  # add base: blue bathymetry and light brown/green topography
  addProviderTiles(
    "Esri.OceanBasemap",
    options = providerTileOptions(
      variant = "Ocean/World_Ocean_Base")) |>
  # add reference: placename labels and borders
  addProviderTiles(
    "Esri.OceanBasemap",
    options = providerTileOptions(
      variant = "Ocean/World_Ocean_Reference"))
class(m)
m
```


```{r}
library(mapview)

# use nc data
nc <- sf::st_read(system.file("shape/nc.shp", package="sf"), quiet=TRUE)

m <- mapView(nc)
slotNames(m)
class(m@map)
mapView(nc)
```


```{r}
library(glue)
library(msens)  # remotes::install_github("MarineSensitivity/msens")

ms_basemap() |> 
  addPolygons(
    data  = nc,
    label = ~NAME,
    popup = ~glue("NAME: {NAME}<br>FIPS: {FIPS}"))
```
