<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ben Best">
<meta name="dcterms.date" content="2026-10-09">

<title>The OBIS-method trial, explained: what we ran on seven species, what it showed, and what it means for modeling 19,000</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="obis_method_explained_files/libs/clipboard/clipboard.min.js"></script>
<script src="obis_method_explained_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="obis_method_explained_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="obis_method_explained_files/libs/quarto-html/popper.min.js"></script>
<script src="obis_method_explained_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="obis_method_explained_files/libs/quarto-html/anchor.min.js"></script>
<link href="obis_method_explained_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="obis_method_explained_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="obis_method_explained_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="obis_method_explained_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="obis_method_explained_files/libs/bootstrap/bootstrap-917079515d91bccb85b543faf8aa8bb6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<!-- msens:analytics:begin -->
<!-- Google tag (gtag.js) — GA4 property 413466008 -->
<!--
  ONE measurement ID across every MarineSensitivity product: gtag scopes the
  `_ga` cookie to the registrable domain, so a single stream spans
  marinesensitivity.org and app.marinesensitivity.org. Products are separated in
  reporting by `content_group` — this site reports as 'workflows'.

  NOTE: do NOT write a literal Liquid include tag anywhere in this file, even
  inside an HTML comment — Liquid parses comments too, so a tag naming this file
  makes it include itself ("stack level too deep", ~10k frames).

  Used TWICE, because the site is half Jekyll and half standalone Quarto output:
    1. a Liquid include of this file in _layouts/default.html — covers the pages
       that carry Jekyll front matter (index, query, compare).
    2. `include-in-header` in ../../_quarto.yml — bakes it into every rendered
       notebook HTML (schema, validate_v7_v8, ingest_*, ...), which Jekyll copies
       verbatim and so never passes through the layout.
  Each page gets exactly one copy; the two paths are disjoint.
-->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-9HW6L751XG"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){ dataLayer.push(arguments); }
  gtag('js', new Date());
  gtag('config', 'G-9HW6L751XG', { content_group: 'workflows' });

  // outbound clicks to the apps / STAC / GitHub — the header nav is the main
  // path from the workflows site into the rest of the toolkit, and a cross-host
  // navigation would otherwise be invisible here.
  document.addEventListener('click', function (e) {
    var a = e.target.closest && e.target.closest('a[href^="http"]');
    if (!a) return;
    var url = new URL(a.href, location.href);
    if (url.hostname === location.hostname) return;
    gtag('event', 'click_outbound', {
      content_group: 'workflows',
      link_domain: url.hostname,
      link_url: a.href.slice(0, 100),
      link_text: (a.textContent || '').trim().slice(0, 100)
    });
  }, true);
</script>
<!-- msens:analytics:end -->


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="1">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-one-paragraph-version" id="toc-the-one-paragraph-version" class="nav-link active" data-scroll-target="#the-one-paragraph-version"><span class="header-section-number">1</span> The one-paragraph version</a></li>
  <li><a href="#why-we-did-this" id="toc-why-we-did-this" class="nav-link" data-scroll-target="#why-we-did-this"><span class="header-section-number">2</span> Why we did this</a></li>
  <li><a href="#how-the-method-works-in-plain-words" id="toc-how-the-method-works-in-plain-words" class="nav-link" data-scroll-target="#how-the-method-works-in-plain-words"><span class="header-section-number">3</span> How the method works, in plain words</a></li>
  <li><a href="#the-six-runs" id="toc-the-six-runs" class="nav-link" data-scroll-target="#the-six-runs"><span class="header-section-number">4</span> The six runs</a></li>
  <li><a href="#what-we-found" id="toc-what-we-found" class="nav-link" data-scroll-target="#what-we-found"><span class="header-section-number">5</span> What we found</a>
  <ul>
  <li><a href="#we-can-reproduce-obiss-models" id="toc-we-can-reproduce-obiss-models" class="nav-link" data-scroll-target="#we-can-reproduce-obiss-models"><span class="header-section-number">5.1</span> We can reproduce OBIS’s models</a></li>
  <li><a href="#our-own-thinning-and-tuning-do-not-hurt" id="toc-our-own-thinning-and-tuning-do-not-hurt" class="nav-link" data-scroll-target="#our-own-thinning-and-tuning-do-not-hurt"><span class="header-section-number">5.2</span> Our own thinning and tuning do not hurt</a></li>
  <li><a href="#the-background-choice-can-make-or-break-a-model" id="toc-the-background-choice-can-make-or-break-a-model" class="nav-link" data-scroll-target="#the-background-choice-can-make-or-break-a-model"><span class="header-section-number">5.3</span> The background choice can make or break a model</a></li>
  <li><a href="#the-loggerhead-the-fit-points-decide-the-footprint" id="toc-the-loggerhead-the-fit-points-decide-the-footprint" class="nav-link" data-scroll-target="#the-loggerhead-the-fit-points-decide-the-footprint"><span class="header-section-number">5.4</span> The loggerhead: the fit points decide the footprint</a></li>
  <li><a href="#the-range-rules-a-to-e" id="toc-the-range-rules-a-to-e" class="nav-link" data-scroll-target="#the-range-rules-a-to-e"><span class="header-section-number">5.5</span> The range rules A to E</a></li>
  </ul></li>
  <li><a href="#what-the-week-of-computing-actually-bought-and-what-it-means-for-19034-species" id="toc-what-the-week-of-computing-actually-bought-and-what-it-means-for-19034-species" class="nav-link" data-scroll-target="#what-the-week-of-computing-actually-bought-and-what-it-means-for-19034-species"><span class="header-section-number">6</span> What the week of computing actually bought, and what it means for 19,034 species</a>
  <ul>
  <li><a href="#where-the-time-went" id="toc-where-the-time-went" class="nav-link" data-scroll-target="#where-the-time-went"><span class="header-section-number">6.1</span> Where the time went</a></li>
  <li><a href="#why-these-seven-are-the-worst-case" id="toc-why-these-seven-are-the-worst-case" class="nav-link" data-scroll-target="#why-these-seven-are-the-worst-case"><span class="header-section-number">6.2</span> Why these seven are the worst case</a></li>
  <li><a href="#is-there-something-faster-than-maxent" id="toc-is-there-something-faster-than-maxent" class="nav-link" data-scroll-target="#is-there-something-faster-than-maxent"><span class="header-section-number">6.3</span> Is there something faster than maxent?</a></li>
  </ul></li>
  <li><a href="#decisions-this-leaves-open" id="toc-decisions-this-leaves-open" class="nav-link" data-scroll-target="#decisions-this-leaves-open"><span class="header-section-number">7</span> Decisions this leaves open</a></li>
  <li><a href="#where-everything-is" id="toc-where-everything-is" class="nav-link" data-scroll-target="#where-everything-is"><span class="header-section-number">8</span> Where everything is</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">The OBIS-method trial, explained: what we ran on seven species, what it showed, and what it means for modeling 19,000</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ben Best </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2026-10-09</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>Written for Ben Best and Tim White as the plain-English companion to <code>obis_range_compare.html</code> and the per-run scorecards. Every number is from <code>data/og/cv_metrics.csv</code>, <code>data/og/timings.csv</code> and the <code>data/og/*_scorecard.csv</code> tables at workflows commit <code>0318fb00</code>, the proposal <code>proposal_MST-supplemental-modeling_round-1.docx</code> (2026-09) and <code>data/obis_sdm_gapfill_species.csv</code>.</p>
</blockquote>
<section id="the-one-paragraph-version" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="the-one-paragraph-version"><span class="header-section-number">1</span> The one-paragraph version</h2>
<p>We took OBIS’s open species-distribution-modeling pipeline (the one the proposal says we will use for 19,000 species), ran it ourselves on the Mac mini for six sea turtles and the North Atlantic right whale, and compared what came out against the models OBIS has already published for those species. Three things came out of it. (1) We can reproduce OBIS’s models: when we feed the pipeline the same points and settings, we get the same answer. (2) One setting matters a lot: where the “background” points come from. Taking them from the species’ own order (turtle records for a turtle) ruins the model; taking them from all air-breathing marine megafauna, or at random, gives models as good as OBIS’s. (3) The loggerhead is a special case: it has 360,000 records, and how many of them you keep to fit the model decides how much of the Pacific it paints. None of this changes the proposal’s compute budget, because the seven species we picked are among the most data-rich marine species on Earth; the typical species in the proposal has 80 occupied cells, not 91,000, and fits in about 15 minutes.</p>
</section>
<section id="why-we-did-this" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="why-we-did-this"><span class="header-section-number">2</span> Why we did this</h2>
<p>The MST scores every species from a habitat-suitability surface. Today those surfaces come from AquaMaps, whose grids FishBase will not release, so a BOEM product built on them is not fully open. OBIS’s framework (<code>obissdm</code> + <code>mpaeu_sdm</code>, built for MPA Europe) is open, uses the same public inputs (OBIS + GBIF records, Bio-ORACLE environmental layers), and fits on the MST’s own 0.05 degree grid. The proposal’s Task 1 is to run it for the 19,034 species the MST scores or could score that OBIS has not modeled yet.</p>
<p>Before promising that, we needed to know three things: can we run the pipeline at all (it was written for OBIS’s cluster), do we get OBIS’s answers back when we do, and which of its settings change the result. We tested on species that matter to BOEM and where we already had something to compare against: OBIS’s published models, IUCN range maps, and the sea-turtle Alaska problem from the v7.1 patch (AquaMaps painted loggerheads into Alaskan waters where there are no records).</p>
</section>
<section id="how-the-method-works-in-plain-words" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="how-the-method-works-in-plain-words"><span class="header-section-number">3</span> How the method works, in plain words</h2>
<p>Every run of the pipeline does the same eight things for one species.</p>
<ol type="1">
<li><strong>Get the records.</strong> Every occurrence of the species in OBIS and GBIF, with OBIS’s quality control (land points, impossible dates, duplicates removed). The loggerhead has 80,012 clean records after this step; the right whale 2,923.</li>
<li><strong>Thin them.</strong> Records cluster where people look (harbors, research cruises, satellite tags). Thinning keeps one record per patch of ocean so the model learns habitat, not effort. What survives are the <strong>fit points</strong>. OBIS’s own thinning turned the loggerhead’s 80,012 records into 1,160 fit points; ours turned them into 23,666 (the two differ in how they choose the thinning distance; more on that below).</li>
<li><strong>Hold some back.</strong> A small set of records (11 to 24 for these species) is set aside before anything is fit. These <strong>evaluation records</strong> are the only truly independent test of the finished model.</li>
<li><strong>Choose background points.</strong> A presence-only model needs to know what “available ocean” looks like, so it draws a sample of places with no record of the species. These are the <strong>background</strong> (about 143,000 cells here). The pipeline’s default is random cells. A common refinement is a <strong>target group</strong>: use places where <em>similar</em> species were recorded, so the background has the same sampling bias as the presences. We tried both and two kinds of target group.</li>
<li><strong>Fit three algorithms.</strong> Maxent (through the <code>maxnet</code> R package, not the Java program), random forest, and XGBoost. Each is tuned by <strong>spatial-block cross-validation</strong>: the ocean is cut into blocks, the model is fit on four fifths of the blocks and tested on the fifth, five times, and the settings that test best are kept.</li>
<li><strong>Accept or reject each algorithm.</strong> An algorithm is kept if its cross-validation Boyce index (CBI) is at least 0.3. The accepted ones are averaged into the <strong>ensemble</strong>.</li>
<li><strong>Predict and threshold.</strong> The ensemble is predicted onto every grid cell, giving a suitability from 0 to 100. The pipeline’s threshold is <strong>P10</strong>: the value that keeps 90 % of the fit points. Cells at or above it are the model’s footprint.</li>
<li><strong>Bootstrap.</strong> The fit is repeated on resamples of the data to produce an uncertainty surface.</li>
</ol>
<p>The scores we report:</p>
<ul>
<li><strong>AUC</strong> (0.5 is a coin flip, 1 is perfect) asks whether the model ranks the held-back records above random background.</li>
<li><strong>CBI</strong> (Boyce index, from -1 to 1) asks whether higher suitability actually means more records; 0 means suitability tells you nothing.</li>
<li><strong>TSS</strong> (true skill statistic, from -1 to 1) scores the footprint after thresholding.</li>
</ul>
<p>We report each twice: on the cross-validation folds (<strong>cv</strong>, what the pipeline’s own gate reads) and on the held-back evaluation records (<strong>eval</strong>, the independent test). The eval sets are tiny, so one eval number is noisy; the pattern across runs is what counts.</p>
</section>
<section id="the-six-runs" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="the-six-runs"><span class="header-section-number">4</span> The six runs</h2>
<p>Each run is a complete pass of the pipeline over the species listed, differing in one or two settings. The acronyms are the folder names in the outputs.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>run</th>
<th>fit points come from</th>
<th>background</th>
<th>species</th>
<th>what it tells us</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>mpaeu</code></td>
<td>OBIS’s published models as downloaded</td>
<td>random</td>
<td>all 7</td>
<td>the reference</td>
</tr>
<tr class="even">
<td><code>ogp</code></td>
<td>OBIS’s exact fit points and tuned settings, re-run by us</td>
<td>random</td>
<td>leatherback, right whale</td>
<td>do we get their answer back</td>
</tr>
<tr class="odd">
<td><code>ogc</code></td>
<td>our thinning, our tuning</td>
<td>random</td>
<td>leatherback, right whale</td>
<td>does our thinning or tuning change anything</td>
</tr>
<tr class="even">
<td><code>og</code></td>
<td>our thinning, our tuning</td>
<td>target group: the species’ order (turtle records for turtles, whale records for the whale)</td>
<td>all 7</td>
<td>the “obvious” target group</td>
</tr>
<tr class="odd">
<td><code>ogm</code></td>
<td>our thinning, our tuning</td>
<td>target group: all air-breathing megafauna (turtles, whales, seals, seabirds)</td>
<td>all 7</td>
<td>a broader target group</td>
</tr>
<tr class="even">
<td><code>ogmp</code></td>
<td>OBIS’s 1,160 fit points, our tuning</td>
<td>megafauna target group</td>
<td>loggerhead</td>
<td>fit points alone, with the background held fixed</td>
</tr>
</tbody>
</table>
<p>One difference applies to all of ours: we used Bio-ORACLE’s surface layers for every species, while OBIS picks surface, water-column or bottom layers by habitat. We did this to keep one environmental stack across the species; it is a setting to revisit.</p>
</section>
<section id="what-we-found" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="what-we-found"><span class="header-section-number">5</span> What we found</h2>
<section id="we-can-reproduce-obiss-models" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="we-can-reproduce-obiss-models"><span class="header-section-number">5.1</span> We can reproduce OBIS’s models</h3>
<p><code>ogp</code> gives back OBIS’s published model within the noise of the tiny evaluation sets: leatherback eval AUC 0.93 against the published 0.94, right whale 0.99 against 0.99. The pipeline runs on our machine, with our patches, and gives their answer. That was not a given; the pipeline assumes OBIS’s storage layout and cluster, and we carry eight small patches to run it here (committed under <code>scripts/og/patches/</code>).</p>
</section>
<section id="our-own-thinning-and-tuning-do-not-hurt" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="our-own-thinning-and-tuning-do-not-hurt"><span class="header-section-number">5.2</span> Our own thinning and tuning do not hurt</h3>
<p><code>ogc</code> (our thinning, our tuning, random background) scores as well as <code>ogp</code> on both species (leatherback 0.97 vs 0.93; right whale 0.99 vs 0.99). So the parts of the pipeline we re-implemented for our grid are not the problem.</p>
</section>
<section id="the-background-choice-can-make-or-break-a-model" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="the-background-choice-can-make-or-break-a-model"><span class="header-section-number">5.3</span> The background choice can make or break a model</h3>
<p>This was the biggest finding. Using the species’ own order as the target group (<code>og</code>) is wrong for these species. For a turtle, “turtle records” are mostly the loggerhead’s own 80,000 records, so presences and background are the same places and the model cannot tell them apart. Every <code>og</code> model scored below its <code>ogm</code> twin on the evaluation records, and the loggerhead <code>og</code> model was <strong>below chance</strong> (eval AUC 0.42). Yet the pipeline accepted it, because its cross-validation CBI was 0.94; the gate reads only CV, and CV shares the same bias. A floor on eval metrics would have caught it. That is a method change to propose to OBIS, not something we changed.</p>
<p>The megafauna target group (<code>ogm</code>) and the random background (<code>ogc</code>, <code>ogp</code>) are both in the same band as OBIS’s published models.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>species</th>
<th>published</th>
<th><code>og</code> (order)</th>
<th><code>ogm</code> (megafauna)</th>
<th><code>ogc</code> (random)</th>
<th><code>ogp</code> (pinned)</th>
<th><code>ogmp</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>loggerhead</td>
<td>0.83 / 0.56 / 0.60</td>
<td><strong>0.42</strong> / -0.21 / 0.03</td>
<td>0.91 / 0.46 / 0.73</td>
<td></td>
<td></td>
<td>0.85 / -0.02 / 0.62</td>
</tr>
<tr class="even">
<td>green</td>
<td>0.88 / 0.38 / 0.49</td>
<td>0.89 / 0.72 / 0.68</td>
<td>0.99 / 0.82 / 0.89</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>hawksbill</td>
<td>0.61 / -0.12 / 0.24</td>
<td>0.75 / -0.15 / 0.48</td>
<td>0.93 / 0.56 / 0.77</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Kemp’s ridley</td>
<td>0.98 / 0.70 / 0.81</td>
<td>0.86 / 0.51 / 0.50</td>
<td>0.91 / 0.54 / 0.67</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>leatherback</td>
<td>0.94 / 0.78 / 0.68</td>
<td>0.63 / -0.10 / 0.30</td>
<td>0.90 / 0.49 / 0.70</td>
<td>0.97 / 0.74 / 0.80</td>
<td>0.93 / 0.78 / 0.65</td>
<td></td>
</tr>
<tr class="even">
<td>olive ridley</td>
<td>1.00 / 0.59 / 0.85</td>
<td>0.98 / 0.69 / 0.80</td>
<td>0.98 / 0.66 / 0.81</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>right whale</td>
<td>0.99 / 0.66 / 0.88</td>
<td>0.84 / 0.47 / 0.65</td>
<td>0.91 / 0.86 / 0.73</td>
<td>0.99 / 0.65 / 0.88</td>
<td>0.99 / 0.69 / 0.86</td>
<td></td>
</tr>
</tbody>
</table>
<p>Ensemble AUC / CBI / TSS on the held-back evaluation records. Read across a row: <code>ogm</code> beats <code>og</code> for every species; <code>ogm</code>, <code>ogc</code> and <code>ogp</code> sit with the published column. The green turtle’s <code>og</code> maxent fit failed outright, so that ensemble is two algorithms.</p>
</section>
<section id="the-loggerhead-the-fit-points-decide-the-footprint" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="the-loggerhead-the-fit-points-decide-the-footprint"><span class="header-section-number">5.4</span> The loggerhead: the fit points decide the footprint</h3>
<p>The loggerhead is the one species where our runs and OBIS’s disagree on the map, and we now know why. Same megafauna background, same tuning, two sets of fit points:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><code>ogm</code> (our 23,666 points)</th>
<th><code>ogmp</code> (OBIS’s 1,160 points)</th>
<th>published</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>eval AUC / CBI / TSS</td>
<td>0.91 / 0.46 / 0.73</td>
<td>0.85 / -0.02 / 0.62</td>
<td>0.83 / 0.56 / 0.60</td>
</tr>
<tr class="even">
<td>fit time</td>
<td>19 h 21 (maxent 18 h 19)</td>
<td>1 h 30</td>
<td>6 h 41 on OBIS’s machine</td>
</tr>
<tr class="odd">
<td>P10 cells, Alaska</td>
<td>0</td>
<td>0</td>
<td>55,807</td>
</tr>
<tr class="even">
<td>P10 cells, Atlantic</td>
<td>32,626</td>
<td>32,532</td>
<td>51,436</td>
</tr>
<tr class="odd">
<td>P10 cells, Gulf of Mexico</td>
<td>11,450</td>
<td>17,439</td>
<td>23,874</td>
</tr>
<tr class="even">
<td>P10 cells, Pacific</td>
<td>55,943</td>
<td>198,141</td>
<td>61,327</td>
</tr>
</tbody>
</table>
<p>Cells are 0.05 degree cells inside each US EEZ subregion above the P10 threshold. With our 23,666 points the Pacific footprint is close to the published one; with OBIS’s 1,160 points it is three times larger. Fewer points, same background, means a looser model. And neither of ours paints a single Alaska cell at P10, where the published model paints 55,807; the published model used OBIS’s depth-layer choice, ours the surface layers, and Alaska is where that difference shows.</p>
<p>The thinning difference is a quirk, not a design choice. The pipeline picks a thinning distance from a spatial-autocorrelation test on a random sample of 1,000 records, and for species with more than 15,000 records it switches to a grid-based prune. OBIS’s sample sent the loggerhead down one branch, ours down the other. The cost of the 23,666-point branch is 18 hours of maxent; the 1,160-point branch costs 1.5 hours and gives a model that is no worse by the gate but paints far more ocean. A fixed cap on fit points, or pinning the published thinning, is the decision to make here.</p>
</section>
<section id="the-range-rules-a-to-e" class="level3" data-number="5.5">
<h3 data-number="5.5" class="anchored" data-anchor-id="the-range-rules-a-to-e"><span class="header-section-number">5.5</span> The range rules A to E</h3>
<p>The scorecards also apply the five range rules we drafted for the v7.1 turtle patch (A: P10 inside the convex hull of the fit points; B to D: add held-out thresholds and uncertainty; E: all of that plus a <strong>regional effort test</strong>, which asks, per EEZ subregion, whether the region has been searched enough for an absence of records to mean anything). The effort test gives the same verdict for every run: Atlantic, Gulf and Pacific “kept”, Alaska “unsearched”. Between our two backgrounds the test agrees in 24 of 24 species-by-subregion cells. It reads records and effort, not the model, so a background change moves it only through which cells are in the P10 footprint to begin with.</p>
<p>Rule E also reaches beyond the convex hull that bounds P10, so for the loggerhead <code>ogm</code> it grows the Pacific from 55,943 to 138,957 cells with thresholds (72 to 81 across folds) at the P10 value (73). Whether that reach is wanted is one of the open choices.</p>
</section>
</section>
<section id="what-the-week-of-computing-actually-bought-and-what-it-means-for-19034-species" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="what-the-week-of-computing-actually-bought-and-what-it-means-for-19034-species"><span class="header-section-number">6</span> What the week of computing actually bought, and what it means for 19,034 species</h2>
<section id="where-the-time-went" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="where-the-time-went"><span class="header-section-number">6.1</span> Where the time went</h3>
<p>The seven species took about three days of machine time, not a week of pure compute; the rest of the week was fetching the pipeline’s inputs (Bio-ORACLE layers, OBIS’s published models, the target-group backgrounds), patching the pipeline to run outside OBIS’s cluster, building the scorecards, and sharing the mini with a CalCOFI release, which held most runs to 2 to 6 cores.</p>
<p>The machine time itself was almost entirely the loggerhead:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>run</th>
<th>species</th>
<th>wall time</th>
<th>of which maxent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>og</code> six</td>
<td>6 (no loggerhead)</td>
<td>fits of 12 to 329 min per species, six in parallel (about 5.5 h), + about 2 h bootstrap</td>
<td>most</td>
</tr>
<tr class="even">
<td><code>ogm</code> six</td>
<td>6</td>
<td>7 h 14 fit + 1 h 50 bootstrap, 6 cores</td>
<td>most</td>
</tr>
<tr class="odd">
<td><code>og</code> loggerhead</td>
<td>1</td>
<td>14 h 35 fit + 5 h bootstrap, 4 cores</td>
<td>13 h 20</td>
</tr>
<tr class="even">
<td><code>ogm</code> loggerhead</td>
<td>1</td>
<td>19 h 21 fit + 5 h bootstrap, 2 cores</td>
<td>18 h 19</td>
</tr>
<tr class="odd">
<td><code>ogmp</code> loggerhead</td>
<td>1</td>
<td>1 h 30 fit + 22 min bootstrap, 2 cores</td>
<td>about 1 h</td>
</tr>
</tbody>
</table>
<p>Per species, fit time is a flat 10 minutes plus about 3 minutes per 100 fit points, and maxent is 91 to 95 % of it. The other two algorithms are cheap: for the loggerhead’s 23,666 points, random forest took 7 minutes and XGBoost 12, against maxent’s 1,099.</p>
</section>
<section id="why-these-seven-are-the-worst-case" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="why-these-seven-are-the-worst-case"><span class="header-section-number">6.2</span> Why these seven are the worst case</h3>
<p>The seven species we chose are freakishly well recorded. Among the 19,034 gap-fill species in the proposal, the median species has <strong>80</strong> occupied 0.05 degree cells worldwide; 90 % have fewer than 500; 99 % fewer than 2,200; only 24 have more than 10,000. The loggerhead has 91,557, the green turtle 23,859, the leatherback 20,181. Our cheapest runs are the right representatives of the proposal’s species: Kemp’s ridley and the right whale, each with 155 fit points, fit in 11 to 15 minutes and bootstrapped in a few more.</p>
<p>Scaling the measured cost (10 min + 0.05 min per fit point, plus 25 % for the bootstrap, as measured on the six) over the real record counts of the 19,034 species gives about <strong>8,000 worker-hours</strong>, or <strong>11 days on a 64-core machine</strong> running 32 two-core workers. Capping fit points at 2,000 (which only touches 231 species) trims that to 7,400. The proposal’s figure, 40 minutes per species, 12,689 core-hours and 8 days on 64 cores, is the right order of magnitude. The expensive tail is a few hundred species, and it is the tail where a cap on fit points, or OBIS’s own thinning, costs nothing in model quality.</p>
</section>
<section id="is-there-something-faster-than-maxent" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="is-there-something-faster-than-maxent"><span class="header-section-number">6.3</span> Is there something faster than maxent?</h3>
<p>The pipeline already uses <code>maxnet</code>, the R re-implementation of Maxent on top of <code>glmnet</code>; there is no Java Maxent in the loop. What makes it slow here is not the algorithm but how it is driven:</p>
<ul>
<li><strong>The tuning grid.</strong> OBIS’s settings try two feature sets (linear + quadratic, and hinge) and four regularization values, each by five-fold cross-validation: 41 maxnet fits per species. The hinge features are the expensive half; they expand every predictor into dozens of columns, and glmnet’s cost grows with columns times rows. <code>obissdm</code>’s own default is linear + quadratic only with four regularization values, 21 fits and no hinge.</li>
<li><strong>The rows.</strong> 143,000 background cells plus the fit points, times five folds, times 41 fits.</li>
<li><strong>The fit points.</strong> Linear in cost, and for the loggerhead 20 times OBIS’s count through the thinning quirk above.</li>
</ul>
<p>So the fastest way to the same answer is to keep OBIS’s thinning as published, drop or shrink the hinge grid, and cap the background for the data-rich species; each is a one-line setting. Beyond that, the evidence from these runs says maxent is not the algorithm carrying the ensemble: in cross-validation, random forest matched or beat maxent for all seven species on the megafauna background (for example loggerhead AUC 0.93 vs 0.92, right whale 0.80 vs 0.74), and the same holds in OBIS’s own published fits (random forest 0.79 to 0.94 against maxent 0.71 to 0.94). Random forest and XGBoost take 3 to 12 minutes each regardless of record count. For the few hundred data-rich species, an ensemble without maxent, or maxent on a light grid, is a defensible way to keep the batch inside the budget; for the 18,000 ordinary species it does not matter, because 10 minutes of fixed cost dominates.</p>
<p>We have not tested a lighter maxent grid or a two-algorithm ensemble on these species yet. Both are cheap to test now that the data and scorecards exist (the whole loop on the right whale is 15 minutes).</p>
</section>
</section>
<section id="decisions-this-leaves-open" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="decisions-this-leaves-open"><span class="header-section-number">7</span> Decisions this leaves open</h2>
<ol type="1">
<li><strong>Background.</strong> Carry the megafauna target group (<code>ogm</code>) or random (<code>ogc</code>) into the batch; never the order-level group. For the 19,034 species, “megafauna” does not generalize; a target group per broad taxon (fish records for fish, and so on) or the random default are the choices. Random is OBIS’s own setting and needs no extra table.</li>
<li><strong>Loggerhead thinning, and the general rule.</strong> Cap fit points (OBIS’s branch gives 1,160; a fixed cap of 2,000 to 5,000 would be explicit), or accept 19-hour fits for the handful of species above 10,000 cells.</li>
<li><strong>Acceptance gate.</strong> Propose to OBIS a floor on the independent evaluation metrics beside the CV Boyce index, so a below-chance model is rejected. Until then we can apply it ourselves when ingesting.</li>
<li><strong>Range rule.</strong> Whether rule E’s reach beyond the fit-point hull is wanted, the 0.25 ratio guard and the 0.5 degree unit of the effort test, and whether a P10 footprint of 51 vs 57 cells for the leatherback is acceptable.</li>
<li><strong>Depth layers.</strong> Re-run with OBIS’s per-habitat layer choice before deciding anything about Alaska.</li>
<li><strong>Compute for the proposal.</strong> The budget line holds. Pin OBIS’s thinning and a light maxent grid in the batch settings; test both on the seven species first (an afternoon).</li>
</ol>
</section>
<section id="where-everything-is" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="where-everything-is"><span class="header-section-number">8</span> Where everything is</h2>
<ul>
<li><strong>Reports</strong> (rendered pages, workflows repo <code>_output/</code>, published at marinesensitivity.org/workflows/): <code>obis_range_compare.html</code> (every run side by side), <code>obis_range_constraint.html</code> (the published models under rules A to E), and one scorecard per run: <code>obis_range_constraint_og.html</code>, <code>_ogm.html</code>, <code>_ogmp.html</code>, <code>_ogp.html</code>. <code>ogc</code> has no card; it is compared in <code>scripts/og/compare_control.R</code>.</li>
<li><strong>Tables</strong> (<code>workflows/data/og/</code>): <code>cv_metrics.csv</code> (every metric above), <code>timings.csv</code> (every step time), and per run <code>{run}_scorecard.csv</code>, <code>{run}_region_test.csv</code>, <code>{run}_heldout_folds.csv</code>.</li>
<li><strong>Code</strong> (<code>workflows/scripts/og/</code>): the run scripts (<code>run_one.sh</code>, <code>run_seven.sh</code>, <code>run_logger_ogm.sh</code>, <code>run_og.R</code>), the scorecard renderer, the metric and timing collectors, the target-group builder, and <code>patches/</code> with the eight patches we apply to OBIS’s pipeline (kept on a local branch of our clone until we decide to fork publicly).</li>
<li><strong>Model outputs</strong> (<code>~/_big/sdm/</code> on the Mac mini and the laptop): <code>og/taxonid=&lt;id&gt;/model=&lt;run&gt;/</code> holds each run’s predictions as COGs, metrics, log and manifest; <code>scorecard/&lt;run&gt;.duckdb</code> the scorecard databases; <code>obis/species/</code> OBIS’s published models; <code>og_inputs/</code> the environmental stack and target-group backgrounds.</li>
<li><strong>The rules in code</strong>: <code>msens::heldout_threshold()</code> and <code>msens::region_effort_test()</code> (msens 0.54.0), with unit tests.</li>
</ul>
<!-- -->

</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "The OBIS-method trial, explained: what we ran on seven species, what it showed, and what it means for modeling 19,000"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Ben Best"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-10-09"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Written for Ben Best and Tim White as the plain-English companion to </span><span class="in">`obis_range_compare.html`</span><span class="at"> and the</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; per-run scorecards. Every number is from </span><span class="in">`data/og/cv_metrics.csv`</span><span class="at">, </span><span class="in">`data/og/timings.csv`</span><span class="at"> and the</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; </span><span class="in">`data/og/*_scorecard.csv`</span><span class="at"> tables at workflows commit </span><span class="in">`0318fb00`</span><span class="at">, the proposal</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; </span><span class="in">`proposal_MST-supplemental-modeling_round-1.docx`</span><span class="at"> (2026-09) and </span><span class="in">`data/obis_sdm_gapfill_species.csv`</span><span class="at">.</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">## The one-paragraph version</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>We took OBIS's open species-distribution-modeling pipeline (the one the proposal says we will use for 19,000 species), ran it ourselves on the Mac mini for six sea turtles and the North Atlantic right whale, and compared what came out against the models OBIS has already published for those species. Three things came out of it. (1) We can reproduce OBIS's models: when we feed the pipeline the same points and settings, we get the same answer. (2) One setting matters a lot: where the "background" points come from. Taking them from the species' own order (turtle records for a turtle) ruins the model; taking them from all air-breathing marine megafauna, or at random, gives models as good as OBIS's. (3) The loggerhead is a special case: it has 360,000 records, and how many of them you keep to fit the model decides how much of the Pacific it paints. None of this changes the proposal's compute budget, because the seven species we picked are among the most data-rich marine species on Earth; the typical species in the proposal has 80 occupied cells, not 91,000, and fits in about 15 minutes.</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why we did this</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>The MST scores every species from a habitat-suitability surface. Today those surfaces come from AquaMaps, whose grids FishBase will not release, so a BOEM product built on them is not fully open. OBIS's framework (<span class="in">`obissdm`</span> + <span class="in">`mpaeu_sdm`</span>, built for MPA Europe) is open, uses the same public inputs (OBIS + GBIF records, Bio-ORACLE environmental layers), and fits on the MST's own 0.05 degree grid. The proposal's Task 1 is to run it for the 19,034 species the MST scores or could score that OBIS has not modeled yet.</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>Before promising that, we needed to know three things: can we run the pipeline at all (it was written for OBIS's cluster), do we get OBIS's answers back when we do, and which of its settings change the result. We tested on species that matter to BOEM and where we already had something to compare against: OBIS's published models, IUCN range maps, and the sea-turtle Alaska problem from the v7.1 patch (AquaMaps painted loggerheads into Alaskan waters where there are no records).</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">## How the method works, in plain words</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>Every run of the pipeline does the same eight things for one species.</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Get the records.** Every occurrence of the species in OBIS and GBIF, with OBIS's quality control (land points, impossible dates, duplicates removed). The loggerhead has 80,012 clean records after this step; the right whale 2,923.</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Thin them.** Records cluster where people look (harbors, research cruises, satellite tags). Thinning keeps one record per patch of ocean so the model learns habitat, not effort. What survives are the **fit points**. OBIS's own thinning turned the loggerhead's 80,012 records into 1,160 fit points; ours turned them into 23,666 (the two differ in how they choose the thinning distance; more on that below).</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Hold some back.** A small set of records (11 to 24 for these species) is set aside before anything is fit. These **evaluation records** are the only truly independent test of the finished model.</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Choose background points.** A presence-only model needs to know what "available ocean" looks like, so it draws a sample of places with no record of the species. These are the **background** (about 143,000 cells here). The pipeline's default is random cells. A common refinement is a **target group**: use places where *similar* species were recorded, so the background has the same sampling bias as the presences. We tried both and two kinds of target group.</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Fit three algorithms.** Maxent (through the `maxnet` R package, not the Java program), random forest, and XGBoost. Each is tuned by **spatial-block cross-validation**: the ocean is cut into blocks, the model is fit on four fifths of the blocks and tested on the fifth, five times, and the settings that test best are kept.</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Accept or reject each algorithm.** An algorithm is kept if its cross-validation Boyce index (CBI) is at least 0.3. The accepted ones are averaged into the **ensemble**.</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>**Predict and threshold.** The ensemble is predicted onto every grid cell, giving a suitability from 0 to 100. The pipeline's threshold is **P10**: the value that keeps 90 % of the fit points. Cells at or above it are the model's footprint.</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>**Bootstrap.** The fit is repeated on resamples of the data to produce an uncertainty surface.</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>The scores we report:</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**AUC** (0.5 is a coin flip, 1 is perfect) asks whether the model ranks the held-back records above random background.</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**CBI** (Boyce index, from -1 to 1) asks whether higher suitability actually means more records; 0 means suitability tells you nothing.</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**TSS** (true skill statistic, from -1 to 1) scores the footprint after thresholding.</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>We report each twice: on the cross-validation folds (**cv**, what the pipeline's own gate reads) and on the held-back evaluation records (**eval**, the independent test). The eval sets are tiny, so one eval number is noisy; the pattern across runs is what counts.</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="fu">## The six runs</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>Each run is a complete pass of the pipeline over the species listed, differing in one or two settings. The acronyms are the folder names in the outputs.</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> run <span class="pp">|</span> fit points come from <span class="pp">|</span> background <span class="pp">|</span> species <span class="pp">|</span> what it tells us <span class="pp">|</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|---|</span></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`mpaeu`</span> <span class="pp">|</span> OBIS's published models as downloaded <span class="pp">|</span> random <span class="pp">|</span> all 7 <span class="pp">|</span> the reference <span class="pp">|</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`ogp`</span> <span class="pp">|</span> OBIS's exact fit points and tuned settings, re-run by us <span class="pp">|</span> random <span class="pp">|</span> leatherback, right whale <span class="pp">|</span> do we get their answer back <span class="pp">|</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`ogc`</span> <span class="pp">|</span> our thinning, our tuning <span class="pp">|</span> random <span class="pp">|</span> leatherback, right whale <span class="pp">|</span> does our thinning or tuning change anything <span class="pp">|</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`og`</span> <span class="pp">|</span> our thinning, our tuning <span class="pp">|</span> target group: the species' order (turtle records for turtles, whale records for the whale) <span class="pp">|</span> all 7 <span class="pp">|</span> the "obvious" target group <span class="pp">|</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`ogm`</span> <span class="pp">|</span> our thinning, our tuning <span class="pp">|</span> target group: all air-breathing megafauna (turtles, whales, seals, seabirds) <span class="pp">|</span> all 7 <span class="pp">|</span> a broader target group <span class="pp">|</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`ogmp`</span> <span class="pp">|</span> OBIS's 1,160 fit points, our tuning <span class="pp">|</span> megafauna target group <span class="pp">|</span> loggerhead <span class="pp">|</span> fit points alone, with the background held fixed <span class="pp">|</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>One difference applies to all of ours: we used Bio-ORACLE's surface layers for every species, while OBIS picks surface, water-column or bottom layers by habitat. We did this to keep one environmental stack across the species; it is a setting to revisit.</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="fu">## What we found</span></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="fu">### We can reproduce OBIS's models</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="in">`ogp`</span> gives back OBIS's published model within the noise of the tiny evaluation sets: leatherback eval AUC 0.93 against the published 0.94, right whale 0.99 against 0.99. The pipeline runs on our machine, with our patches, and gives their answer. That was not a given; the pipeline assumes OBIS's storage layout and cluster, and we carry eight small patches to run it here (committed under <span class="in">`scripts/og/patches/`</span>).</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="fu">### Our own thinning and tuning do not hurt</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="in">`ogc`</span> (our thinning, our tuning, random background) scores as well as <span class="in">`ogp`</span> on both species (leatherback 0.97 vs 0.93; right whale 0.99 vs 0.99). So the parts of the pipeline we re-implemented for our grid are not the problem.</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="fu">### The background choice can make or break a model</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>This was the biggest finding. Using the species' own order as the target group (<span class="in">`og`</span>) is wrong for these species. For a turtle, "turtle records" are mostly the loggerhead's own 80,000 records, so presences and background are the same places and the model cannot tell them apart. Every <span class="in">`og`</span> model scored below its <span class="in">`ogm`</span> twin on the evaluation records, and the loggerhead <span class="in">`og`</span> model was **below chance** (eval AUC 0.42). Yet the pipeline accepted it, because its cross-validation CBI was 0.94; the gate reads only CV, and CV shares the same bias. A floor on eval metrics would have caught it. That is a method change to propose to OBIS, not something we changed.</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>The megafauna target group (<span class="in">`ogm`</span>) and the random background (<span class="in">`ogc`</span>, <span class="in">`ogp`</span>) are both in the same band as OBIS's published models.</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> species <span class="pp">|</span> published <span class="pp">|</span> <span class="in">`og`</span> (order) <span class="pp">|</span> <span class="in">`ogm`</span> (megafauna) <span class="pp">|</span> <span class="in">`ogc`</span> (random) <span class="pp">|</span> <span class="in">`ogp`</span> (pinned) <span class="pp">|</span> <span class="in">`ogmp`</span> <span class="pp">|</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|---|---|---|</span></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> loggerhead <span class="pp">|</span> 0.83 / 0.56 / 0.60 <span class="pp">|</span> **0.42** / -0.21 / 0.03 <span class="pp">|</span> 0.91 / 0.46 / 0.73 <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> 0.85 / -0.02 / 0.62 <span class="pp">|</span></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> green <span class="pp">|</span> 0.88 / 0.38 / 0.49 <span class="pp">|</span> 0.89 / 0.72 / 0.68 <span class="pp">|</span> 0.99 / 0.82 / 0.89 <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> hawksbill <span class="pp">|</span> 0.61 / -0.12 / 0.24 <span class="pp">|</span> 0.75 / -0.15 / 0.48 <span class="pp">|</span> 0.93 / 0.56 / 0.77 <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Kemp's ridley <span class="pp">|</span> 0.98 / 0.70 / 0.81 <span class="pp">|</span> 0.86 / 0.51 / 0.50 <span class="pp">|</span> 0.91 / 0.54 / 0.67 <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> leatherback <span class="pp">|</span> 0.94 / 0.78 / 0.68 <span class="pp">|</span> 0.63 / -0.10 / 0.30 <span class="pp">|</span> 0.90 / 0.49 / 0.70 <span class="pp">|</span> 0.97 / 0.74 / 0.80 <span class="pp">|</span> 0.93 / 0.78 / 0.65 <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> olive ridley <span class="pp">|</span> 1.00 / 0.59 / 0.85 <span class="pp">|</span> 0.98 / 0.69 / 0.80 <span class="pp">|</span> 0.98 / 0.66 / 0.81 <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> right whale <span class="pp">|</span> 0.99 / 0.66 / 0.88 <span class="pp">|</span> 0.84 / 0.47 / 0.65 <span class="pp">|</span> 0.91 / 0.86 / 0.73 <span class="pp">|</span> 0.99 / 0.65 / 0.88 <span class="pp">|</span> 0.99 / 0.69 / 0.86 <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>Ensemble AUC / CBI / TSS on the held-back evaluation records. Read across a row: <span class="in">`ogm`</span> beats <span class="in">`og`</span> for every species; <span class="in">`ogm`</span>, <span class="in">`ogc`</span> and <span class="in">`ogp`</span> sit with the published column. The green turtle's <span class="in">`og`</span> maxent fit failed outright, so that ensemble is two algorithms.</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a><span class="fu">### The loggerhead: the fit points decide the footprint</span></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>The loggerhead is the one species where our runs and OBIS's disagree on the map, and we now know why. Same megafauna background, same tuning, two sets of fit points:</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="pp">|</span> <span class="in">`ogm`</span> (our 23,666 points) <span class="pp">|</span> <span class="in">`ogmp`</span> (OBIS's 1,160 points) <span class="pp">|</span> published <span class="pp">|</span></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> eval AUC / CBI / TSS <span class="pp">|</span> 0.91 / 0.46 / 0.73 <span class="pp">|</span> 0.85 / -0.02 / 0.62 <span class="pp">|</span> 0.83 / 0.56 / 0.60 <span class="pp">|</span></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> fit time <span class="pp">|</span> 19 h 21 (maxent 18 h 19) <span class="pp">|</span> 1 h 30 <span class="pp">|</span> 6 h 41 on OBIS's machine <span class="pp">|</span></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> P10 cells, Alaska <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span> 55,807 <span class="pp">|</span></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> P10 cells, Atlantic <span class="pp">|</span> 32,626 <span class="pp">|</span> 32,532 <span class="pp">|</span> 51,436 <span class="pp">|</span></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> P10 cells, Gulf of Mexico <span class="pp">|</span> 11,450 <span class="pp">|</span> 17,439 <span class="pp">|</span> 23,874 <span class="pp">|</span></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> P10 cells, Pacific <span class="pp">|</span> 55,943 <span class="pp">|</span> 198,141 <span class="pp">|</span> 61,327 <span class="pp">|</span></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>Cells are 0.05 degree cells inside each US EEZ subregion above the P10 threshold. With our 23,666 points the Pacific footprint is close to the published one; with OBIS's 1,160 points it is three times larger. Fewer points, same background, means a looser model. And neither of ours paints a single Alaska cell at P10, where the published model paints 55,807; the published model used OBIS's depth-layer choice, ours the surface layers, and Alaska is where that difference shows.</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>The thinning difference is a quirk, not a design choice. The pipeline picks a thinning distance from a spatial-autocorrelation test on a random sample of 1,000 records, and for species with more than 15,000 records it switches to a grid-based prune. OBIS's sample sent the loggerhead down one branch, ours down the other. The cost of the 23,666-point branch is 18 hours of maxent; the 1,160-point branch costs 1.5 hours and gives a model that is no worse by the gate but paints far more ocean. A fixed cap on fit points, or pinning the published thinning, is the decision to make here.</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="fu">### The range rules A to E</span></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>The scorecards also apply the five range rules we drafted for the v7.1 turtle patch (A: P10 inside the convex hull of the fit points; B to D: add held-out thresholds and uncertainty; E: all of that plus a **regional effort test**, which asks, per EEZ subregion, whether the region has been searched enough for an absence of records to mean anything). The effort test gives the same verdict for every run: Atlantic, Gulf and Pacific "kept", Alaska "unsearched". Between our two backgrounds the test agrees in 24 of 24 species-by-subregion cells. It reads records and effort, not the model, so a background change moves it only through which cells are in the P10 footprint to begin with.</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>Rule E also reaches beyond the convex hull that bounds P10, so for the loggerhead <span class="in">`ogm`</span> it grows the Pacific from 55,943 to 138,957 cells with thresholds (72 to 81 across folds) at the P10 value (73). Whether that reach is wanted is one of the open choices.</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="fu">## What the week of computing actually bought, and what it means for 19,034 species</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="fu">### Where the time went</span></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>The seven species took about three days of machine time, not a week of pure compute; the rest of the week was fetching the pipeline's inputs (Bio-ORACLE layers, OBIS's published models, the target-group backgrounds), patching the pipeline to run outside OBIS's cluster, building the scorecards, and sharing the mini with a CalCOFI release, which held most runs to 2 to 6 cores.</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>The machine time itself was almost entirely the loggerhead:</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> run <span class="pp">|</span> species <span class="pp">|</span> wall time <span class="pp">|</span> of which maxent <span class="pp">|</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`og`</span> six <span class="pp">|</span> 6 (no loggerhead) <span class="pp">|</span> fits of 12 to 329 min per species, six in parallel (about 5.5 h), + about 2 h bootstrap <span class="pp">|</span> most <span class="pp">|</span></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`ogm`</span> six <span class="pp">|</span> 6 <span class="pp">|</span> 7 h 14 fit + 1 h 50 bootstrap, 6 cores <span class="pp">|</span> most <span class="pp">|</span></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`og`</span> loggerhead <span class="pp">|</span> 1 <span class="pp">|</span> 14 h 35 fit + 5 h bootstrap, 4 cores <span class="pp">|</span> 13 h 20 <span class="pp">|</span></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`ogm`</span> loggerhead <span class="pp">|</span> 1 <span class="pp">|</span> 19 h 21 fit + 5 h bootstrap, 2 cores <span class="pp">|</span> 18 h 19 <span class="pp">|</span></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`ogmp`</span> loggerhead <span class="pp">|</span> 1 <span class="pp">|</span> 1 h 30 fit + 22 min bootstrap, 2 cores <span class="pp">|</span> about 1 h <span class="pp">|</span></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>Per species, fit time is a flat 10 minutes plus about 3 minutes per 100 fit points, and maxent is 91 to 95 % of it. The other two algorithms are cheap: for the loggerhead's 23,666 points, random forest took 7 minutes and XGBoost 12, against maxent's 1,099.</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a><span class="fu">### Why these seven are the worst case</span></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>The seven species we chose are freakishly well recorded. Among the 19,034 gap-fill species in the proposal, the median species has **80** occupied 0.05 degree cells worldwide; 90 % have fewer than 500; 99 % fewer than 2,200; only 24 have more than 10,000. The loggerhead has 91,557, the green turtle 23,859, the leatherback 20,181. Our cheapest runs are the right representatives of the proposal's species: Kemp's ridley and the right whale, each with 155 fit points, fit in 11 to 15 minutes and bootstrapped in a few more.</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>Scaling the measured cost (10 min + 0.05 min per fit point, plus 25 % for the bootstrap, as measured on the six) over the real record counts of the 19,034 species gives about **8,000 worker-hours**, or **11 days on a 64-core machine** running 32 two-core workers. Capping fit points at 2,000 (which only touches 231 species) trims that to 7,400. The proposal's figure, 40 minutes per species, 12,689 core-hours and 8 days on 64 cores, is the right order of magnitude. The expensive tail is a few hundred species, and it is the tail where a cap on fit points, or OBIS's own thinning, costs nothing in model quality.</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a><span class="fu">### Is there something faster than maxent?</span></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>The pipeline already uses <span class="in">`maxnet`</span>, the R re-implementation of Maxent on top of <span class="in">`glmnet`</span>; there is no Java Maxent in the loop. What makes it slow here is not the algorithm but how it is driven:</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**The tuning grid.** OBIS's settings try two feature sets (linear + quadratic, and hinge) and four regularization values, each by five-fold cross-validation: 41 maxnet fits per species. The hinge features are the expensive half; they expand every predictor into dozens of columns, and glmnet's cost grows with columns times rows. <span class="in">`obissdm`</span>'s own default is linear + quadratic only with four regularization values, 21 fits and no hinge.</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**The rows.** 143,000 background cells plus the fit points, times five folds, times 41 fits.</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**The fit points.** Linear in cost, and for the loggerhead 20 times OBIS's count through the thinning quirk above.</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>So the fastest way to the same answer is to keep OBIS's thinning as published, drop or shrink the hinge grid, and cap the background for the data-rich species; each is a one-line setting. Beyond that, the evidence from these runs says maxent is not the algorithm carrying the ensemble: in cross-validation, random forest matched or beat maxent for all seven species on the megafauna background (for example loggerhead AUC 0.93 vs 0.92, right whale 0.80 vs 0.74), and the same holds in OBIS's own published fits (random forest 0.79 to 0.94 against maxent 0.71 to 0.94). Random forest and XGBoost take 3 to 12 minutes each regardless of record count. For the few hundred data-rich species, an ensemble without maxent, or maxent on a light grid, is a defensible way to keep the batch inside the budget; for the 18,000 ordinary species it does not matter, because 10 minutes of fixed cost dominates.</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>We have not tested a lighter maxent grid or a two-algorithm ensemble on these species yet. Both are cheap to test now that the data and scorecards exist (the whole loop on the right whale is 15 minutes).</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a><span class="fu">## Decisions this leaves open</span></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Background.** Carry the megafauna target group (<span class="in">`ogm`</span>) or random (<span class="in">`ogc`</span>) into the batch; never the order-level group. For the 19,034 species, "megafauna" does not generalize; a target group per broad taxon (fish records for fish, and so on) or the random default are the choices. Random is OBIS's own setting and needs no extra table.</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Loggerhead thinning, and the general rule.** Cap fit points (OBIS's branch gives 1,160; a fixed cap of 2,000 to 5,000 would be explicit), or accept 19-hour fits for the handful of species above 10,000 cells.</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Acceptance gate.** Propose to OBIS a floor on the independent evaluation metrics beside the CV Boyce index, so a below-chance model is rejected. Until then we can apply it ourselves when ingesting.</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Range rule.** Whether rule E's reach beyond the fit-point hull is wanted, the 0.25 ratio guard and the 0.5 degree unit of the effort test, and whether a P10 footprint of 51 vs 57 cells for the leatherback is acceptable.</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Depth layers.** Re-run with OBIS's per-habitat layer choice before deciding anything about Alaska.</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Compute for the proposal.** The budget line holds. Pin OBIS's thinning and a light maxent grid in the batch settings; test both on the seven species first (an afternoon).</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a><span class="fu">## Where everything is</span></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Reports** (rendered pages, workflows repo <span class="in">`_output/`</span>, published at marinesensitivity.org/workflows/): <span class="in">`obis_range_compare.html`</span> (every run side by side), <span class="in">`obis_range_constraint.html`</span> (the published models under rules A to E), and one scorecard per run: <span class="in">`obis_range_constraint_og.html`</span>, <span class="in">`_ogm.html`</span>, <span class="in">`_ogmp.html`</span>, <span class="in">`_ogp.html`</span>. <span class="in">`ogc`</span> has no card; it is compared in <span class="in">`scripts/og/compare_control.R`</span>.</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Tables** (<span class="in">`workflows/data/og/`</span>): <span class="in">`cv_metrics.csv`</span> (every metric above), <span class="in">`timings.csv`</span> (every step time), and per run <span class="in">`{run}_scorecard.csv`</span>, <span class="in">`{run}_region_test.csv`</span>, <span class="in">`{run}_heldout_folds.csv`</span>.</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Code** (<span class="in">`workflows/scripts/og/`</span>): the run scripts (<span class="in">`run_one.sh`</span>, <span class="in">`run_seven.sh`</span>, <span class="in">`run_logger_ogm.sh`</span>, <span class="in">`run_og.R`</span>), the scorecard renderer, the metric and timing collectors, the target-group builder, and <span class="in">`patches/`</span> with the eight patches we apply to OBIS's pipeline (kept on a local branch of our clone until we decide to fork publicly).</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Model outputs** (<span class="in">`~/_big/sdm/`</span> on the Mac mini and the laptop): <span class="in">`og/taxonid=&lt;id&gt;/model=&lt;run&gt;/`</span> holds each run's predictions as COGs, metrics, log and manifest; <span class="in">`scorecard/&lt;run&gt;.duckdb`</span> the scorecard databases; <span class="in">`obis/species/`</span> OBIS's published models; <span class="in">`og_inputs/`</span> the environmental stack and target-group backgrounds.</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**The rules in code**: <span class="in">`msens::heldout_threshold()`</span> and <span class="in">`msens::region_effort_test()`</span> (msens 0.54.0), with unit tests.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>