# alias of the STAC root catalog on the main site ----
#
# The static STAC root catalog is built by msens::stac_build() and deployed at
# https://file.marinesensitivity.org/stac/catalog.json (a release is registered into it by
# msens::stac_catalog_register() in backfill_versions.qmd, and deployed by the `deploy` chunk of
# release_marine-atlas.qmd). The main site (repo MarineSensitivity.github.io, GitHub Pages, a
# different origin) serves an ALIAS of that root at https://marinesensitivity.org/stac/catalog.json,
# with every child link absolute, because the stac-sdm extension's examples name THAT address.
#
# The alias used to be regenerated by hand (stac/update.sh in the site repo) and so lagged every
# release. This is the same step as a function of the pipeline:
#
#   stac_alias_sync()               # compare only; WARN (never stop) when the alias lags
#   STAC_ALIAS_PUSH=1 ...           # write + commit + push the site repo, then wait for Pages
#
# the alias legitimately lags at the moment a release is registered (the root just changed), so a
# difference is a WARN naming the missing/extra children, not an error; publishing it is a
# deliberate act (STAC_ALIAS_PUSH=1) because it pushes another repo's main branch.

# child collection ids ("v7", "v9", ...) named by a parsed catalog's `child` links ----
stac_alias_children <- function(cat) {
  h <- unlist(lapply(cat$links, \(l) if (identical(l$rel, "child")) l$href))
  if (is.null(h)) character() else h
}

# the live alias, parsed; a cache-buster keeps GitHub Pages' 10-min CDN copy out of the compare ----
stac_alias_read_live <- function(self_url) {
  u <- paste0(self_url, "?cb=", as.integer(Sys.time()))
  jsonlite::fromJSON(u, simplifyVector = FALSE)
}

stac_alias_sync <- function(
    site_repo = here::here("../MarineSensitivity.github.io"),
    src       = paste0(msens::atlas_bases()$stac, "/catalog.json"),
    self_url  = "https://marinesensitivity.org/stac/catalog.json",
    push      = nzchar(Sys.getenv("STAC_ALIAS_PUSH"))) {

  # 1. build the alias from the DEPLOYED root; round-trip it through the writer so what is
  #    compared is exactly what a push would publish (number/empty-list encodings included) ----
  alias  <- tryCatch(msens::stac_catalog_alias(src, self_url = self_url), error = \(e) {
    # a compare-only call must never abort a release over a network blip; a push must
    if (push) stop(e)
    logger::log_warn("STAC alias not checked: cannot build it from {src}: {conditionMessage(e)}")
    NULL })
  if (is.null(alias)) return(invisible(NULL))
  f_new  <- tempfile("stac_alias_", fileext = ".json")
  on.exit(unlink(f_new), add = TRUE)
  msens::stac_catalog_alias_write(alias, f_new)
  built  <- jsonlite::fromJSON(f_new, simplifyVector = FALSE)
  stopifnot("the alias has no child collections" = length(stac_alias_children(built)) > 0)

  # 2. compare with the live alias ----
  live <- tryCatch(stac_alias_read_live(self_url), error = \(e) {
    logger::log_warn("cannot read the live alias {self_url}: {conditionMessage(e)}")
    NULL })
  if (!is.null(live) && identical(live, built)) {
    logger::log_info("STAC alias current: {self_url} matches the root catalog ({length(stac_alias_children(built))} children)")
    return(invisible(NULL))
  }

  kid_id  <- \(h) basename(dirname(h))
  b_kids  <- stac_alias_children(built)
  l_kids  <- if (is.null(live)) character() else stac_alias_children(live)
  diff    <- list(
    missing = kid_id(setdiff(b_kids, l_kids)),    # in the root, absent from the live alias
    extra   = kid_id(setdiff(l_kids, b_kids)))    # in the live alias, gone from the root
  diff$other_fields_differ <- !is.null(live) && !length(diff$missing) && !length(diff$extra)
  msg <- paste0(
    "missing from the live alias: ", if (length(diff$missing)) paste(diff$missing, collapse = ", ") else "none",
    "; extra in the live alias: ",   if (length(diff$extra))   paste(diff$extra,   collapse = ", ") else "none",
    if (diff$other_fields_differ) "; children match, other fields differ" else "")

  # 3. different, not pushing: report and return (the alias lags at registration time) ----
  if (!push) {
    logger::log_warn("STAC alias {self_url} is out of date -- {msg}. STAC_ALIAS_PUSH=1 publishes it.")
    return(invisible(diff))
  }

  # 4. different and pushing: write, commit ONLY the alias, push main, wait for Pages ----
  git <- \(...) {
    o <- system2("git", c("-C", shQuote(site_repo), ...), stdout = TRUE, stderr = TRUE)
    if (!is.null(attr(o, "status")) && attr(o, "status") != 0)
      stop("git ", paste(c(...), collapse = " "), " failed: ", paste(o, collapse = "\n"), call. = FALSE)
    o
  }
  stopifnot(
    "site repo checkout is missing (STAC_ALIAS_PUSH needs MarineSensitivity.github.io)" =
      dir.exists(file.path(site_repo, ".git")))
  branch <- git("rev-parse", "--abbrev-ref", "HEAD")
  stopifnot("site repo is not on main; refusing to push the STAC alias" = identical(branch, "main"),
            "site repo has other staged changes; refusing to commit the STAC alias" =
              !length(git("diff", "--cached", "--name-only")))

  f_site <- file.path(site_repo, "stac", "catalog.json")
  dir.create(dirname(f_site), showWarnings = FALSE, recursive = TRUE)
  msens::stac_catalog_alias_write(alias, f_site)
  git("add", "stac/catalog.json")
  kids <- paste(kid_id(b_kids), collapse = " ")
  if (!length(git("diff", "--cached", "--name-only"))) {
    logger::log_info("STAC alias file already matches the site repo; nothing to commit (Pages may still be building)")
  } else {
    git("commit", "-q", "-m", shQuote(paste0("stac: alias of the root catalog regenerated (children: ", kids, ")")),
        "--", "stac/catalog.json")
    git("push", "origin", "main")
    logger::log_info("STAC alias pushed to the site repo (children: {kids}); waiting for GitHub Pages")
  }

  # poll the live alias until it IS what was written (CI publishes in ~1 min) ----
  t0 <- Sys.time()
  repeat {
    live <- tryCatch(stac_alias_read_live(self_url), error = \(e) NULL)
    if (!is.null(live) && identical(live, built)) break
    if (as.numeric(difftime(Sys.time(), t0, units = "secs")) > 180)
      stop("the live STAC alias ", self_url, " did not become the pushed alias within 3 min; check the site CI",
           call. = FALSE)
    Sys.sleep(10)
  }
  logger::log_info("STAC alias published and verified at {self_url} (children: {kids})")
  invisible(diff)
}
